### ISSUE TITLE
Binary file format

### ISSUE THREAD

**Issue by noytzach** [SalvatoreDiGirolamo/tracevis#1]
What format should I provide as binary?

**Comment by SalvatoreDiGirolamo** [comment]
Hey, that is the ELF with the code you execute and that is then used to fill the "slm" files.

**Comment by noytzach** [comment]
Thank you. I got lots of error messages when I ran it, so I assumed I was giving it the wrong file.

Apparently `addr2line` installed on my machine (2.20.51.0.2-5.44.el6) does not support the `-a` option you are using. I removed the flag and the script works as expected.

Thanks again. Closing this issue.

**Comment by SalvatoreDiGirolamo** [comment]
Ah ok, I see. I added a note to the README. Thanks!
