### ISSUE TITLE
Example binary , ask and trace file

### ISSUE THREAD

**Issue by lighteningfingers** [SalvatoreDiGirolamo/tracevis#2]
Please could you add an example binary assembler and trace to the repository.

This will allow a known good set of required files to pipeclean the install requirements and an example trace in chrome.

**Comment by SalvatoreDiGirolamo** [comment]
Hey, I added an example with a binary, the raw traces, and the parsed trace to feed to chrome. You can find it in example/ (also check the updated README.md). ;)
